name: Build jars

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
        
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: buildJars --stacktrace --debug
        
    - name: Prep files
      run: |
        for f in ./build/*.jar; do mv "$f" "$(echo "$f" | sed -E 's/(.+)-(.+)-.+-(.+)/\1-\2-${{ steps.short-sha.outputs.sha }}-\3/')"; done
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "build-${{ steps.short-sha.outputs.sha }}"
        path: ./build/
